$(function () {
//=include /partials/00_data.js'
//=include /partials/01_startgame.js' 
//=include /partials/02_endgame.js'
//=include /partials/03_levelUp.js'
//=include /partials/04_consoles.js'
//=include /partials/05_hero_base.js'
//=include /partials/05_hero_refresh.js'
//=include /partials/06_enemy.js'
//=include /partials/07_mercenaries.js'
//=include /partials/08_inventory_armory.js'
//=include /partials/08_inventory_mechanics.js'
//=include /partials/09_poems_book.js'
//=include /partials/09_poems_effects.js'
//=include /partials/09_poems_pick.js'
//=include /partials/09_poems_theory.js'
//=include /partials/10_supporting.js'
//=include /partials/11_developer.js'
//=include /partials/12_resume.js'
})